"use client";import type{ReactNode}from"react";import{Filter,Grid2X2,LayoutList,LoaderCircle,RefreshCw,Search,X}from"lucide-react";
export function Button({variant="secondary",children,...p}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"danger"}){return<button className={`btn ${variant}`} {...p}>{children}</button>}
export function ContextHeader({title,eyebrow,meta,actions}:{title:string;eyebrow?:string;meta?:string;actions?:ReactNode}){return<header className="context-header"><div><span>{eyebrow||"AICS Lab"}</span><h1>{title}</h1>{meta&&<p>{meta}</p>}</div>{actions&&<div className="context-actions">{actions}</div>}</header>}
export function Toolbar({search=true,filters=true,view,onView,action}:{search?:boolean;filters?:boolean;view?:"board"|"list";onView?:(v:"board"|"list")=>void;action?:ReactNode}){return<div className="toolbar"><div>{search&&<button><Search size={17}/>Search</button>}{filters&&<button><Filter size={16}/>Filter</button>}</div>{view&&<div className="view-toggle"><button className={view==="board"?"active":""} onClick={()=>onView?.("board")}><Grid2X2 size={17}/></button><button className={view==="list"?"active":""} onClick={()=>onView?.("list")}><LayoutList size={17}/></button></div>}<div>{action}</div></div>}
export function Modal({title,children,onClose,footer}:{title:string;children:ReactNode;onClose:()=>void;footer?:ReactNode}){return<div className="overlay"><section className="modal" role="dialog" aria-modal="true"><header><h2>{title}</h2><button className="icon-btn" onClick={onClose}><X size={19}/></button></header><div className="modal-content">{children}</div>{footer&&<footer>{footer}</footer>}</section></div>}
export function Drawer({title,children,onClose,footer}:{title:string;children:ReactNode;onClose:()=>void;footer?:ReactNode}){return<div className="overlay drawer-overlay"><aside className="drawer"><header><h2>{title}</h2><button className="icon-btn" onClick={onClose}><X size={19}/></button></header><div className="drawer-content">{children}</div>{footer&&<footer>{footer}</footer>}</aside></div>}
export function Field({label,children}:{label:string;children:ReactNode}){return<label className="field"><span>{label}</span>{children}</label>}
export function Loading(){return<div className="state"><LoaderCircle className="spin" size={20}/>불러오는 중입니다.</div>}
export function Empty({title,description}:{title:string;description:string}){return<div className="state empty"><strong>{title}</strong><span>{description}</span></div>}
export function ErrorBox({message,retry}:{message:string;retry?:()=>void}){return<div className="state error"><strong>{message}</strong>{retry&&<Button onClick={retry}><RefreshCw size={15}/>다시 시도</Button>}</div>}
export function Message({children,tone="info"}:{children:ReactNode;tone?:"info"|"error"|"success"}){return<div className={`message ${tone}`}>{children}</div>}
