"use client";
import { useCallback, useMemo, useState } from "react"; import { ChevronLeft,ChevronRight,Plus,SlidersHorizontal } from "lucide-react"; import { api } from "../lib/api"; import { asArray,useResource } from "../lib/hooks"; import { Button,ErrorState,Field,LoadingState,Modal,Notice,PageHeader } from "../components/ui";
const weekdays=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
function monthCells(date:Date){const first=new Date(date.getFullYear(),date.getMonth(),1);const offset=(first.getDay()+6)%7;const start=new Date(date.getFullYear(),date.getMonth(),1-offset);return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d;});}
export default function CalendarPage(){const [month,setMonth]=useState(new Date());const [modal,setModal]=useState<"create"|"detail"|null>(null);const [selected,setSelected]=useState<Record<string,any>|null>(null);const [errorMsg,setErrorMsg]=useState("");
 const query=`?from=${new Date(month.getFullYear(),month.getMonth(),1).toISOString()}&to=${new Date(month.getFullYear(),month.getMonth()+1,0,23,59,59).toISOString()}`; const loader=useCallback(()=>api.calendar.list(query),[query]);const state=useResource(loader);const events=asArray(state.data);const cells=useMemo(()=>monthCells(month),[month]);
 function move(n:number){setMonth(new Date(month.getFullYear(),month.getMonth()+n,1))} async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setErrorMsg("");const b=Object.fromEntries(new FormData(e.currentTarget));try{await api.calendar.create(b);setModal(null);await state.reload();}catch(e){setErrorMsg(e instanceof Error?e.message:"일정을 저장하지 못했습니다.")}}
 async function remove(){if(!selected?.id)return;try{await api.calendar.remove(String(selected.id));setModal(null);await state.reload();}catch(e){setErrorMsg(e instanceof Error?e.message:"삭제하지 못했습니다.")}}
 return <><PageHeader title="Calendar" description="연구실 일정과 반복 일정을 관리합니다." action={<Button variant="primary" onClick={()=>setModal("create")}><Plus size={16}/>Event</Button>}/><div className="calendar-toolbar"><div><Button onClick={()=>setMonth(new Date())}>Today</Button><button className="icon-button" onClick={()=>move(-1)} aria-label="이전 달"><ChevronLeft/></button><button className="icon-button" onClick={()=>move(1)} aria-label="다음 달"><ChevronRight/></button><h2>{month.getFullYear()}년 {month.getMonth()+1}월</h2></div><div><Button>Month <ChevronRight size={14}/></Button><Button><SlidersHorizontal size={15}/>Filter</Button></div></div><section className="calendar-workspace">{state.loading?<LoadingState/>:state.error?<ErrorState message={state.error} retry={state.reload}/>:<><div className="weekday-row">{weekdays.map(w=><span key={w}>{w}</span>)}</div><div className="month-grid">{cells.map((d,i)=>{const key=d.toISOString().slice(0,10);const dayEvents=events.filter(e=>String(e.startAt||e.start||e.date||"").slice(0,10)===key);return <div className={`day-cell ${d.getMonth()!==month.getMonth()?"outside":""}`} key={key}><span className={key===new Date().toISOString().slice(0,10)?"today-number":""}>{d.getDate()}</span>{dayEvents.slice(0,3).map((e,j)=><button className="calendar-event" key={String(e.id||j)} onClick={()=>{setSelected(e);setModal("detail")}}><i/>{String(e.title||"일정")}</button>)}{dayEvents.length>3&&<small>+{dayEvents.length-3} more</small>}</div>})}</div></>}</section>
 {modal==="create"&&<Modal title="Add Event" onClose={()=>setModal(null)} footer={null}><form onSubmit={create}><Field label="일정 제목"><input name="title" required/></Field><div className="field-row"><Field label="시작"><input type="datetime-local" name="startAt" required/></Field><Field label="종료"><input type="datetime-local" name="endAt" required/></Field></div><Field label="설명"><textarea name="description" rows={3}/></Field><Field label="반복 규칙 (선택)"><input name="rrule" placeholder="예: FREQ=WEEKLY"/></Field>{errorMsg&&<Notice tone="error">{errorMsg}</Notice>}<div className="form-actions"><Button type="button" onClick={()=>setModal(null)}>Cancel</Button><Button variant="primary">Create</Button></div></form></Modal>}
 {modal==="detail"&&selected&&<Modal title={String(selected.title||"Event")} onClose={()=>setModal(null)} footer={<><Button variant="danger" onClick={remove}>Delete</Button><Button onClick={()=>setModal(null)}>Close</Button></>}><dl className="detail-list">{Object.entries(selected).filter(([,v])=>typeof v!=="object").slice(0,8).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl>{errorMsg&&<Notice tone="error">{errorMsg}</Notice>}<p className="muted-note">반복 일정의 exception·split 작업은 해당 일정 ID와 API 명세를 사용해 처리됩니다.</p></Modal>}</>}
