export const labelMap = {
  general: "일반",
  important: "중요",
  account_info: "계정",
  schedule: "일정",
  meeting: "미팅",
  deadline: "마감",
  event: "행사",
  trip: "출장",
  other: "기타",
  shared: "공유",
  personal: "개인",
  present: "출석",
  absent: "결석",
  leave: "휴가",
  half_leave: "반차",
  pending: "대기",
  approved: "승인",
  rejected: "반려",
  deactivated: "비활성",
  purchased: "구매 완료",
  delivered: "입고 완료",
  active: "진행",
  closed: "종료",
  watch: "주의",
  writing: "작성 중",
  submitted: "제출",
  under_review: "심사 중",
  accepted: "채택",
  published: "출판",
  paper: "논문",
  presentation: "발표",
  template: "템플릿",
  software: "소프트웨어",
  member: "구성원",
  manager: "관리자",
  admin: "최고 관리자",
  research: "연구비",
  operation: "운영비",
  conference: "학회",
  equipment: "장비",
  office: "사무",
  infra: "인프라",
  billing: "결제",
  library: "라이브러리",
  annual: "연차",
  half_day: "반차",
  sick: "병가",
  public: "공개",
  private: "비공개",
  sci: "SCI",
  kci: "KCI",
  intl_conf: "국제 학회",
  domestic_conf: "국내 학회",
  undergrad: "학부",
  master: "석사",
  phd: "박사",
  professor: "교수",
  ko: "한국어",
  en: "영어",
  unknown: "알 수 없음",
};

export function getLabel(value) {
  const key = String(value || "").toLowerCase();
  return labelMap[key] || value || "-";
}

const toneMap = {
  important: "danger",
  pending: "warning",
  approved: "success",
  accepted: "success",
  published: "success",
  present: "success",
  active: "success",
  delivered: "success",
  rejected: "danger",
  deactivated: "muted",
  absent: "danger",
  closed: "muted",
  watch: "warning",
  purchased: "primary",
  manager: "primary",
  admin: "danger",
  deadline: "warning",
  trip: "primary",
  shared: "primary",
  private: "muted",
};

export default function Badge({ value, children, tone }) {
  const key = String(value || "").toLowerCase();
  const badgeTone = tone || toneMap[key] || "neutral";

  return <span className={`badge badge-${badgeTone}`}>{children || getLabel(value)}</span>;
}
